### ISSUE TITLE
A Logo Proposal

### ISSUE THREAD

**Issue by LuigiBaute** [terdia/legato-framework#1]
Greetings,
I've noticed this project and see that it doesn't have a logo,
I'm a Graphic Designer I could give you a logo proposal if you wish,
If this is something that may be of the interest of this project, let me know

Cheers! Luigi.

**Comment by terdia** [comment]
@LuigiBaute it won't be a bad idea, looking forward to seeing what you come up with

**Comment by LuigiBaute** [comment]
Ok I'll start working on it, the name of the logo should be ''legato'', right? @terdia

**Comment by terdia** [comment]
yes

**Comment by terdia** [comment]
Maybe knowing what Legato means can give more inspiration - https://en.wikipedia.org/wiki/Legato

**Comment by LuigiBaute** [comment]
Hello @terdia this is what I came up with, If you like the idea and want a different color variation let me know, any suggestion is welcome. Cheers!

![logotipo legato](https://user-images.githubusercontent.com/36426974/40090654-22ad806e-5881-11e8-953a-7eee52ce3854.png)

**Comment by terdia** [comment]
The last row is preferred so far, can it be improved?

**Comment by LuigiBaute** [comment]
Sure, which color you liked the most? how do you want me to improve it? @terdia

**Comment by terdia** [comment]
@LuigiBaute this one -  ![image](https://user-images.githubusercontent.com/4749721/40159553-6eff26e6-59dc-11e8-9445-5919f887e04f.png)

**Comment by LuigiBaute** [comment]
I should submit a pull request with the resizable png plus the monochromatics, and all its files in a google drive, is that good?
@terdia

**Comment by LuigiBaute** [comment]
how about?

**Comment by LuigiBaute** [comment]
![logotipo legato propuesta 2](https://user-images.githubusercontent.com/36426974/40208015-69a6630c-5a05-11e8-8222-b1dde60ea804.jpg)

**Comment by terdia** [comment]
This 
![image](https://user-images.githubusercontent.com/4749721/40213805-ff1a0d38-5a89-11e8-8a47-3e6c0a0ed117.png)

without the line is okay

**Comment by LuigiBaute** [comment]
Hello @terdia ,

![2](https://user-images.githubusercontent.com/36426974/40283605-e4bbcfbe-5c4e-11e8-9686-2bbbb8fd6377.png)

I really like this logo I think It'll suit your project very well :+1: 
Can I submit it in a Pull Request?

**Comment by terdia** [comment]
Yes @LuigiBaute  please do, thanks for your help

**Comment by LuigiBaute** [comment]
@terdia should I create a new file for the logo or just upload it on an specific file already created?

**Comment by terdia** [comment]
Maybe add a logo folder and out it inside

**Comment by LuigiBaute** [comment]
I've submitted the pull request now, thank you for letting me be a part of this really cool project! 

Best regards!

**Comment by terdia** [comment]
Thanks a great deal. I will pull and check later.

**Comment by terdia** [comment]
Closing this issues

**Comment by LuigiBaute** [comment]
Best regards @terdia
 I'd like to know more about the details of this project, I read the link you sended but it gave me abstracts ideas about it, this project is about ''music sequencers, instrument controllers, fingerboards, guitar synthesizers, wind controllers, and electronic drums. Synthesizers without built-in controllers are often called sound modules, and are controlled via USB, MIDI or CV/gate using a controller device, often a MIDI keyboard or other controller.'' ? If you'd like me to update the read me to give more specific details about the project, I could do that :+1:

**Comment by terdia** [comment]
OOPS no this is actually a PHP framework, you can read more more in the documentation https://docs.legatoframework.com

**Comment by LuigiBaute** [comment]
That explains everything pretty well, If I could suggest is for you to add that link to the project description and the content of the site to the project read.me I think it would be easier for a newcomer to this project to understand it! thanks! @terdia
